from ordered_vector import  VetorOrdenadoCrescenteInt
import numpy as np

vetor = VetorOrdenadoCrescenteInt(100)
vetor.inserir(1)
vetor.inserir(2)
vetor.inserir(3)
vetor.inserir(4)
vetor.inserir(5)
vetor.inserir(6)
vetor.inserir(7)
vetor.inserir(8)
vetor.inserir(9)
vetor.inserir(10)
vetor.inserir(11)
vetor.inserir(12)
vetor.inserir(13)
vetor.inserir(14)
vetor.inserir(15)
vetor.inserir(16)
vetor.inserir(17)
vetor.inserir(18)
vetor.inserir(19)
vetor.inserir(20)
vetor.inserir(21)
vetor.inserir(22)
vetor.inserir(23)
vetor.inserir(24)
vetor.inserir(25)
vetor.inserir(26)
vetor.inserir(27)
vetor.inserir(28)
vetor.inserir(29)

print(vetor.pesquisar_binario(28))
